services:
  rust-expo-push-notification-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ../:/workspace
    working_dir: /workspace
